@startuml Cadastro de Usuário
salt
{
  {+
    Selecione o tipo de perfil:
    [[Empresa] [Coordenação] [Professor] [Aluno]]
  }
  {+
    Formulário
    E-mail / Matrícula: [_________________]
    Nome: [_________________]
    Senha: [_________________]
    [Submeter]
  }
}

@enduml
