@startuml Formulário_Projeto
salt
{
  {+
    Formulário do Projeto
    Título: [_________________]
    Descrição: [__________________________]
    Requisitos: [_________________________]
    [Submeter] [Cancelar]
  }
}

@enduml
