@startmindmap mapamental
* Sistema de Gerenciamento de Projetos
** Usuários do Sistema
*** Empresas externas 
**** Cadastrar projetos
**** Acompanhar status
**** Avaliar resultados
*** Coordenação 
**** Aprovar projetos
**** Gerenciar usuários
**** Gerar relatórios
*** Professores 
**** Orientar projetos
**** Avaliar entregas
**** Interagir com alunos
*** Alunos 
**** Ser alocado em projetos
**** Submeter entregas
**** Acompanhar feedback

** Estrutura / Funcionalidades
*** Home (sem login) 
**** Hall da Fama
**** Como Funciona
***** Empresa cadastra projeto
***** Coordenação aprova
***** Professor gerencia
***** Aluno executa
**** Botões: Cadastro / Login
*** Autenticação 
**** Cadastro
***** Selecionar tipo de perfil
***** Formulário: e-mail/matrícula, nome, senha
**** Login
***** Formulário: e-mail/matrícula, senha

** Dashboards
*** Empresa
**** Cadastrar novo projeto
**** Listar projetos com status
**** Acompanhar andamento
*** Coordenação
**** Lista de projetos para análise
***** Aprovar / Recusar / Solicitar ajustes
**** Selecionar professor responsável
**** Lista de projetos em andamento
*** Professor
**** Lista de projetos designados
**** Selecionar alunos participantes
**** Acompanhar atividades
**** Dar feedback
*** Aluno
**** Projetos designados
**** Realizar entregas
**** Acompanhar feedback

** Notificações 
*** Aprovação de projeto
*** Professor designado
*** Aluno alocado
*** Feedback recebido
@endmindmap


