@startuml aluno
salt
{
  {+
    Projetos Designados
    [◀] 
    [Projeto X | Status: Em andamento | [Entrar]] 
    [Projeto Y | Status: Em andamento | [Entrar]] 
    [Projeto Z | Status: Em andamento | [Entrar]] 
    [▶]
  }
}
@enduml
