@startuml Empresa
salt
{
  {+
    [Cadastrar novo projeto]
  }

  {+
    Projetos Cadastrados
    [◀] [Projeto X - Pendente] [Projeto Y - Aprovado] [Projeto Z - Recusado] [▶]
  }
}

@enduml
